/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    Grid: (typeof import('./components/Grid/index.vue'))['default']
    GridItem: (typeof import('./components/Grid/components/GridItem.vue'))['default']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    IconCommunity: (typeof import('./components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./components/icons/IconTooling.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SearchForm: (typeof import('./components/SearchForm/index.vue'))['default']
    SearchFormItem: (typeof import('./components/SearchForm/components/SearchFormItem.vue'))['default']
    TheWelcome: (typeof import('./components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./components/WelcomeItem.vue'))['default']
  }
}
